project:
  type: website
  output-dir: ../guskathol.github.io

website:
  title: "Blog R"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/guskathol
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

execute: 
  freeze: auto

